### PR TITLE
Add support for react >= 15.6

### PR DESCRIPTION
**Pull request by Lctrs**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by Lctrs** [comment]
Should I also bump `admin-on-rest` dep constraint to `^1.3` to avoid potential same problem with previous versions ?

**Comment by soyuka** [comment]
> Should I also bump admin-on-rest dep constraint to ^1.3 to avoid potential same problem with previous versions ?

You can.

**Comment by Lctrs** [comment]
Do you have any idea why it fails now ? `react` is listed in the lockfile so I don't see why it can't find it.

**Comment by soyuka** [comment]
Okay so my bad, please keep the react hard dependencies and remove peer dependencies. Indeed `admin-on-rest` has them under `devDependencies` and `peerDependencies`. This way, it won't be installed twice in production builds.

**Comment by dunglas** [comment]
React as a peer dependency is usually a bad idea: https://github.com/yahoo/react-intl/issues/79

**Comment by Lctrs** [comment]
@soyuka Is that what you had in mine ?

**Comment by soyuka** [comment]
Yes. Keep the same constraint on react versions as admin-on-rest though `^15.4.0 || ^16.0.0-beta.5`

**Comment by soyuka** [comment]
Thanks @Lctrs

**Pull request merged**
